package:
  name: roq-risk-manager
  version: 1.0

source:
  git_url: ..

build:
  skip: true  # [not unix]

requirements:
  build:
    - {{ compiler('cxx') }}
    - clangdev
    - cmake
    - make
    - pkg-config
  host:
    - abseil-cpp
    - boost-cpp
    - catch2
    - nlohmann_json
    - roq-adapter
    - roq-client
    - roq-flags
    - roq-io
    - roq-oss-benchmark
    - roq-oss-tomlplusplus
    - roq-web
    - sqlite

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Roq's Risk Manager (a template project)
